"""add etf_composition

Revision ID: 0c4340728f1a
Revises: ba1ac58560ee
Create Date: 2026-08-15 21:40:42.909362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types  # noqa: F401  autogenerate references app.db_types.Money/Quantity by name but never imports the module itself


revision: str = '0c4340728f1a'
down_revision: Union[str, None] = 'ba1ac58560ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_composition',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('weight_pct', app.db_types.Quantity(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'dimension', 'category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etf_composition')
    # ### end Alembic commands ###
