"""add price_source, daily_snapshot, snapshot_watermark

Revision ID: 0d10df0f0f69
Revises: 6fce2c6bea1a
Create Date: 2026-08-15 11:49:26.599725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types  # noqa: F401  autogenerate references app.db_types.Money/Quantity by name but never imports the module itself


revision: str = '0d10df0f0f69'
down_revision: Union[str, None] = '6fce2c6bea1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshot',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=False),
    sa.Column('quantity', app.db_types.Quantity(), nullable=True),
    sa.Column('value_eur', app.db_types.Money(), nullable=False),
    sa.Column('cost_basis_eur', app.db_types.Money(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'scope_type', 'scope_id')
    )
    op.create_table('price_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_symbol', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_watermark',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('dirty_from_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_watermark')
    op.drop_table('price_source')
    op.drop_table('daily_snapshot')
    # ### end Alembic commands ###
