"""add txn split_ratio and payload_hash

Revision ID: 6fce2c6bea1a
Revises: d5de2859e684
Create Date: 2026-08-15 11:27:26.628778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types  # noqa: F401  autogenerate references app.db_types.Money/Quantity by name but never imports the module itself


revision: str = '6fce2c6bea1a'
down_revision: Union[str, None] = 'd5de2859e684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.Enum('MANUAL', 'AGENT', 'IMPORT', name='txnsource'), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('diff_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_ratio', app.db_types.Quantity(), nullable=True))
        batch_op.add_column(sa.Column('payload_hash', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.drop_column('payload_hash')
        batch_op.drop_column('split_ratio')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
