"""add cpi_index_point

Revision ID: ba1ac58560ee
Revises: fb5b0b0e8490
Create Date: 2026-08-15 18:53:01.286163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types  # noqa: F401  autogenerate references app.db_types.Money/Quantity by name but never imports the module itself


revision: str = 'ba1ac58560ee'
down_revision: Union[str, None] = 'fb5b0b0e8490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpi_index_point',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('index_value', app.db_types.Quantity(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpi_index_point')
    # ### end Alembic commands ###
