"""add instrument, txn, import_batch, price_point, fx_rate

Revision ID: d5de2859e684
Revises: 750ba3eef915
Create Date: 2026-08-15 11:20:35.706232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types

revision: str = 'd5de2859e684'
down_revision: Union[str, None] = '750ba3eef915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate',
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('eur_rate', app.db_types.Quantity(), nullable=False),
    sa.PrimaryKeyConstraint('currency', 'date')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AGENT', 'IMPORT', name='txnsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('wkn', sa.String(length=6), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('asset_class', sa.Enum('EQUITY', 'BOND', 'COMMODITY', 'CRYPTO', 'REAL_ESTATE', 'VEHICLE', 'CASH', 'LIABILITY', name='assetclass'), nullable=False),
    sa.Column('valuation_mode', sa.Enum('MARKET', 'ANCHORED', 'MODELED', 'AMORTIZING_LIABILITY', 'NOMINAL', name='valuationmode'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('liquidity_tier', sa.Enum('T0', 'T1', 'T2', 'T3', name='liquiditytier'), nullable=True),
    sa.Column('ter_pct', app.db_types.Quantity(), nullable=True),
    sa.Column('fine_weight_g', app.db_types.Quantity(), nullable=True),
    sa.Column('valuation_config_json', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('price_point',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', app.db_types.Quantity(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'date')
    )
    op.create_table('txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_precision', sa.Enum('DAY', 'MONTH', 'QUARTER', 'YEAR', name='dateprecision'), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'INTEREST', 'FEE', 'TAX', 'DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'SPLIT', 'VALUATION', 'OPENING_BALANCE', 'BALANCE_STATEMENT', 'LOAN_PAYMENT', 'EXTRA_REPAYMENT', name='transactiontype'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('quantity', app.db_types.Quantity(), nullable=True),
    sa.Column('price', app.db_types.Quantity(), nullable=True),
    sa.Column('price_mode', sa.Enum('EXACT', 'AUTO', name='pricemode'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', app.db_types.Quantity(), nullable=True),
    sa.Column('fees', app.db_types.Money(), nullable=False),
    sa.Column('tax', app.db_types.Money(), nullable=False),
    sa.Column('amount_eur', app.db_types.Money(), nullable=False),
    sa.Column('counter_account_id', sa.Integer(), nullable=True),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_batch_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AGENT', 'IMPORT', name='txnsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['counter_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['voided_by_batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('txn')
    op.drop_table('price_point')
    op.drop_table('instrument')
    op.drop_table('import_batch')
    op.drop_table('fx_rate')
    # ### end Alembic commands ###
