"""add valuation_anchor, loan, house_price_index_point

Revision ID: fb5b0b0e8490
Revises: 9052f31fa8aa
Create Date: 2026-08-15 14:13:25.495388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db_types  # noqa: F401  autogenerate references app.db_types.Money/Quantity by name but never imports the module itself


revision: str = 'fb5b0b0e8490'
down_revision: Union[str, None] = '9052f31fa8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_price_index_point',
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('index_value', app.db_types.Quantity(), nullable=False),
    sa.PrimaryKeyConstraint('series', 'date')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('principal', app.db_types.Money(), nullable=False),
    sa.Column('rate_pct', app.db_types.Quantity(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('fixed_until', sa.Date(), nullable=True),
    sa.Column('monthly_payment', app.db_types.Money(), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('extra_repayment_allowance_pct', app.db_types.Quantity(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_anchor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_eur', app.db_types.Money(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_anchor')
    op.drop_table('loan')
    op.drop_table('house_price_index_point')
    # ### end Alembic commands ###
